# .readthedocs.yml
version: 2
build:
   os: ubuntu-22.04
   tools:
      python: "3.10"
   requirements_file: docs/requirements.txt
sphinx:
   configuration: docs/conf.py
conda:
  environment: env.yml
