# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

conda:
  environment: env.yml

python:
  virtualenv:
    system_site_packages: false
    extras: ['-vvv']
  pip_install: true
  requirements_file: docs/requirements.txt