# .readthedocs.yml
version: 2
python:
   version: 3.10
   setup_py_install: true
   virtualenv:
      system_site_packages: false
      extras: ['-vvv']
   pip_install: true

build:
   os: ubuntu-22.04
   tools:
      python: "3.10"
sphinx:
   configuration: docs/conf.py
conda:
  environment: env.yml
