# .readthedocs.yml
version: 2
build:
   os: ubuntu-22.04
   tools:
      python: "3.9"
sphinx:
   configuration: docs/conf.py
conda:
   environment: env.yml
python:
   install:
      - method: pip
      path: .
      - requirements: docs/requirements.txt
      extra_requirements:
         - development
