# .readthedocs.yml
version: 2
build:
   os: ubuntu-22.04
   tools:
      python: "3.9"
sphinx:
   configuration: docs/conf.py
conda:
   environment: env.yml
python:
   install:
      - requirements: docs/requirements.txt
submodules:
   exclude: all
