version: 2.1

jobs:
  build_and_test_linux:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: |
            pip install -e ".[develop]" 
      - run:
          command: |
            pytest
workflows:
  main:
    jobs:
      - build_and_test_linux
