version: 2.1

orbs:
  python_linux: circleci/python@2.1.1

jobs:
  install_and_test_linux:
    executor: python_linux/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: |
            pip install -e ".[develop]" 
      - run:
          command: |
            pytest
  build:
    executor: python_linux/default
    steps:
      - checkout
      - run:
          command: |
            python3 setup.py sdist bdist_wheel
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip install pipenv
            pipenv install dist/*
            pipenv install pytest 
workflows:
  main:
    jobs:
      - install_and_test_linux
      - build
